import type { ReactNode } from 'react';
import { household, advisors } from '@/data/clients';
import { formatDate } from '@/lib/format';

interface ReportShellProps {
  title: string;
  asOfDate: string;
  currency?: string;
  children: ReactNode;
  footer?: ReactNode;
}

/**
 * Cover-page style frame that wraps every rendered sample report —
 * mimics a printed wealth report page (header band + body + footer).
 */
export default function ReportShell({ title, asOfDate, currency = 'CAD', children, footer }: ReportShellProps) {
  return (
    <div className="rounded-xl border border-[#e9ecef] bg-white shadow-sm overflow-hidden">
      {/* Header band */}
      <div className="border-b border-[#e9ecef] bg-gradient-to-r from-[#0645ad] to-[#0a5bd6] px-7 py-5 text-white">
        <div className="flex items-start justify-between gap-6">
          <div>
            <div className="text-[11px] font-semibold uppercase tracking-wider text-white/70">Wealth Report</div>
            <h2 className="mt-0.5 text-xl font-semibold leading-tight text-white">{title}</h2>
            <div className="mt-1 text-sm text-white/85">{household.name}</div>
          </div>
          <div className="shrink-0 text-right text-sm">
            <div className="text-white/70 text-[11px] uppercase tracking-wider">As of</div>
            <div className="font-semibold">{formatDate(asOfDate)}</div>
            <div className="mt-2 text-white/70 text-[11px] uppercase tracking-wider">Currency</div>
            <div className="font-semibold">{currency}</div>
          </div>
        </div>
        <div className="mt-4 flex flex-wrap items-center gap-x-6 gap-y-1 border-t border-white/15 pt-3 text-[12px] text-white/80">
          <span>
            <span className="text-white/60">Prepared for:</span> Daniel Okafor
          </span>
          <span>
            <span className="text-white/60">Prepared by:</span>{' '}
            {advisors.map((a) => a.name).join(', ')}
          </span>
          <span>
            <span className="text-white/60">Advisor:</span> {household.advisor}
          </span>
        </div>
      </div>

      {/* Body */}
      <div className="px-7 py-6">{children}</div>

      {/* Footer */}
      <div className="border-t border-[#f0f2f4] bg-[#fafbfc] px-7 py-3 text-[11px] text-[#9aa5b1]">
        {footer ?? (
          <div className="flex flex-wrap items-center justify-between gap-2">
            <span>Values shown in {currency}. FX rate USD/CAD 1.3660 as of {formatDate(asOfDate)}.</span>
            <span>Generated by Reporting · by Purpose</span>
          </div>
        )}
      </div>
    </div>
  );
}
